### ISSUE TITLE
ruckus/foundry master issue list (os 10.0.10 - layer 3 code)

### ISSUE THREAD

**Issue by inphobia** [netdisco/snmp-info#518]
intro:
running 10.0.10c code on icx7850. ruckus/commscope stated starting with v10 only the layer3/router codebase will be made available. layer2/switch codebase is eol.
most of the reports i read regarding foundry seem to be related to the layer3 image. i'm leaning towards leaving the current foundry module as-is, it seems to work fine for layer2 images, and creating a new module for layer3 code.

list of things i noticed/want to do:
- [ ] pretty print model name
- [ ] addresses list the correct ip's but also adds a bunch of network addresses
- [ ] vrrp-e ip's are nowhere to be found
- [ ] vlan overview is empty
- [ ] tagged/untagged vlans/interface are empty
- [ ] configured speed/duplex is exposed via snmp but not polled
- [ ] lags don't show members
- [ ] interface names don't match cli
- [ ] brocade-mct-cluster-mib not available on my devices
- [ ] find out where neighbor entries with ip 254.128.0.0 come from (cant even find this in a complete tech support)
- [ ] verify poe (current hardware only had transceiver slots)

references to relevant brocade/foundry/ruckus mentions:
https://github.com/netdisco/snmp-info/issues/100  port-channel (aggregate) support 
https://github.com/netdisco/snmp-info/issues/224 Problem with port naming on brocade ICX switches - doesn't appear to use ifName table
https://github.com/netdisco/snmp-info/issues/339 Incorrect Vlan Membership results on Ruckus ICX 7XXX switches
https://github.com/netdisco/snmp-info/issues/356 Suspected deprecated OID for Brocade (foundry) devices
https://github.com/netdisco/netdisco/issues/856 Brocade ICX IronWare Addresses and VLANs detection issue
https://github.com/netdisco/netdisco/issues/1138 Brocade/Ruckus switches running router code discovery and control

references to other brocade/foundry/ruckus issues that i haven't or cant reproduce
https://github.com/netdisco/snmp-info/issues/291 arpnip on Extreme VDX switches only gets IPv6 addresses
https://github.com/netdisco/snmp-info/issues/433 Ruckus Vlan Change on port: "VLAN set not supported."
